# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ec2acb8c0af03c321e63462534e24e1ada735085a0f8dfe4d764107ec02e4b30d4947e46b9e80422cdce90f7c44acee570d23281d10cff87b4437b1a1a7c958

test:
  secret_key_base: d1caa9801276879e5864f42b5edf45f0e4b50952eb1ffc74321325712a873fc4726834937eaac275be33bc6fb6093240e11c6dd3c70a6b5ec4aa4e364d963aca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
